Repository ManageIQ/more_core_extensions, pull requests merged in 2020-07, with the labels that each got.

#85 Update pause/resume specs to use ps command
  more_core_extensions.gemspec
  spec/core_ext/process/pause_resume_spec.rb
Labels: bug

#81 Extend the Digest::UUID module with the clean method
  lib/more_core_extensions/all.rb
  lib/more_core_extensions/core_ext/digest.rb
  lib/more_core_extensions/core_ext/digest/uuid.rb
  spec/core_ext/digest/uuid_spec.rb
Labels: enhancement

#87 remove color from length count
  lib/more_core_extensions/core_ext/array/tableize.rb
  spec/core_ext/array/tableize_spec.rb
Labels: enhancement

#91 Add deep_clone and deep_delete
  README.md
  lib/more_core_extensions/core_ext/array/deletes.rb
  lib/more_core_extensions/core_ext/hash/deletes.rb
  lib/more_core_extensions/core_ext/shared/nested.rb
  spec/core_ext/array/deletes_spec.rb
  spec/core_ext/hash/deletes_spec.rb
  spec/core_ext/shared/nested_spec.rb
Labels: enhancement

#90 Update current rubies, loosen older ruby versions
  .travis.yml
Labels: test

#89 Add bundler inject
  .travis.yml
  Gemfile
Labels: dependencies, developer
